
export const cities = [
  {
    name: 'TP. Hồ Chí Minh',
    districts: [
      'Quận 1',
      'Quận 3',
      'Quận 4',
      'Quận 5',
      'Quận 6',
      'Quận 7',
      'Quận 8',
      'Quận 10',
      'Quận 11',
      'Quận 12',
      'Quận Bình Tân',
      'Quận Bình Thạnh',
      'Quận Gò Vấp',
      'Quận Phú Nhuận',
      'Quận Tân Bình',
      'Quận Tân Phú',
      'Thành phố Thủ Đức',
      'Huyện Bình Chánh',
      'Huyện Cần Giờ',
      'Huyện Củ Chi',
      'Huyện Hóc Môn',
      'Huyện Nhà Bè',
    ],
  },
];

export const wardsByDistrict: Record<string, string[]> = {
  'Quận 1': [
    'Phường Bến Nghé',
    'Phường Bến Thành',
    'Phường Cô Giang',
    'Phường Cầu Kho',
    'Phường Cầu Ông Lãnh',
    'Phường Đa Kao',
    'Phường Nguyễn Thái Bình',
    'Phường Nguyễn Cư Trinh',
    'Phường Phạm Ngũ Lão',
    'Phường Tân Định',
  ],
  'Quận 3': [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
  ],
  'Quận 5': [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15',
  ],
  'Quận 7': [
    'Phường Tân Phú',
    'Phường Tân Phong',
    'Phường Tân Hưng',
    'Phường Tân Kiểng',
    'Phường Tân Quy',
    'Phường Phú Mỹ',
    'Phường Bình Thuận',
    'Phường Phú Thuận',
    'Phường Tân Thuận Đông',
    'Phường Tân Thuận Tây',
  ],
  'Quận 10': [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15',
  ],
  'Quận Bình Thạnh': [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15',
    'Phường 17',
    'Phường 19',
    'Phường 21',
    'Phường 22',
    'Phường 24',
    'Phường 25',
    'Phường 26',
    'Phường 27',
    'Phường 28',
  ],
  'Quận Phú Nhuận': [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 13',
    'Phường 15',
    'Phường 17',
  ],
  'Quận Tân Bình': [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15',
  ],
  'Quận Gò Vấp': [
    'Phường 1',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15',
    'Phường 16',
    'Phường 17',
  ],
  'Quận Thủ Đức': [
    'Phường Bình Chiểu',
    'Phường Bình Thọ',
    'Phường Hiệp Bình Chánh',
    'Phường Hiệp Bình Phước',
    'Phường Linh Chiểu',
    'Phường Linh Đông',
    'Phường Linh Tây',
    'Phường Linh Trung',
    'Phường Linh Xuân',
    'Phường Tam Bình',
    'Phường Tam Phú',
    'Phường Trường Thọ',
  ],
  'Huyện Bình Chánh': [
    'Thị trấn Tân Túc',
    'Xã An Phú Tây',
    'Xã Bình Chánh',
    'Xã Bình Hưng',
    'Xã Bình Lợi',
    'Xã Đa Phước',
    'Xã Hưng Long',
    'Xã Lê Minh Xuân',
    'Xã Phạm Văn Hai',
    'Xã Phong Phú',
    'Xã Quy Đức',
    'Xã Tân Kiên',
    'Xã Tân Nhựt',
    'Xã Vĩnh Lộc A',
    'Xã Vĩnh Lộc B',
  ],
  'Huyện Hóc Môn': [
    'Thị trấn Hóc Môn',
    'Xã Bà Điểm',
    'Xã Đông Thạnh',
    'Xã Nhị Bình',
    'Xã Tân Hiệp',
    'Xã Tân Thới Nhì',
    'Xã Tân Xuân',
    'Xã Thới Tam Thôn',
    'Xã Trung Chánh',
    'Xã Xuân Thới Đông',
    'Xã Xuân Thới Sơn',
    'Xã Xuân Thới Thượng',
  ],
};