export const HCM_ADDRESS_DATA = {
  'TP. Hồ Chí Minh': {
    'Quận 1': {
      wards: [
        'Phường Bến Nghé',
        'Phường Bến Thành',
        'Phường Cầu Kho',
        'Phường Cầu Ông Lãnh',
        'Phường Cô Giang',
        'Phường Đa Kao',
        'Phường Nguyễn Cư Trinh',
        'Phường Nguyễn Thái Bình',
        'Phường Phạm Ngũ Lão',
        'Phường Tân Định',
      ],
      streets: [
        'Alexandre de Rhodes',
        'Bà Lê Chân',
        'Bến Chương Dương',
        'Bùi Thị Xuân',
        'Bùi Viện',
        'Calmette',
        'Cách Mạng Tháng 8',
        'Cao Bá Nhạ',
        'Cao Bá Quát',
        'Cây Điệp',
        'Chu Mạnh Chinh',
        'Cô Bắc',
        'Cô Giang',
        'Cống Quỳnh',
        'Điện Biên Phủ',
        'Đồng Khởi',
        'Hai Bà Trưng',
        'Hàm Nghi',
        'Hồ Huấn Nghiệp',
        'Huỳnh Khương Ninh',
        'Huỳnh Thúc Kháng',
        'Khánh Hội',
        'Ký Con',
        'Lê Anh Xuân',
        'Lê Công Kiều',
        'Lê Duẩn',
        'Lê Lai',
        'Lê Lợi',
        'Lê Thánh Tôn',
        'Lý Tự Trọng',
        'Mạc Đĩnh Chi',
        'Mạc Thị Bưởi',
        'Nam Kỳ Khởi Nghĩa',
        'Ngô Đức Kế',
        'Nguyễn Bỉnh Khiêm',
        'Nguyễn Cảnh Chân',
        'Nguyễn Cư Trinh',
        'Nguyễn Du',
        'Nguyễn Huệ',
        'Nguyễn Hữu Cảnh',
        'Nguyễn Hữu Cầu',
        'Nguyễn Huy Tự',
        'Nguyễn Khắc Nhu',
        'Nguyễn Phi Khanh',
        'Nguyễn Siêu',
        'Nguyễn Thái Bình',
        'Nguyễn Thái Học',
        'Nguyễn Thành Ý',
        'Nguyễn Thị Minh Khai',
        'Nguyễn Trãi',
        'Nguyễn Văn Bình',
        'Nguyễn Văn Cừ',
        'Nguyễn Văn Nguyễn',
        'Nguyễn Văn Thủ',
        'Pasteur',
        'Phạm Ngũ Lão',
        'Phan Kế Bính',
        'Phan Liêm',
        'Phan Ngữ',
        'Phan Tôn',
        'Phan Văn Đạt',
        'Phan Văn Trường',
        'Phó Đức Chính',
        'Phùng Khắc Khoan',
        'Sương Nguyệt Ánh',
        'Thạch Thị Thanh',
        'Thái Văn Lung',
        'Thi Sách',
        'Tôn Đức Thắng',
        'Trần Cao Vân',
        'Trần Đình Xu',
        'Trần Hưng Đạo',
        'Trần Nhật Duật',
        'Trần Quang Khải',
        'Trương Định',
        'Yersin',
      ],
    },
    'Quận 3': {
      wards: [
        'Phường 1',
        'Phường 2',
        'Phường 3',
        'Phường 4',
        'Phường 5',
        'Phường 9',
        'Phường 10',
        'Phường 11',
        'Phường 12',
        'Phường 13',
        'Phường 14',
        'Phường Võ Thị Sáu',
      ],
      streets: [
        'Bà Huyện Thanh Quan',
        'Bàn Cờ',
        'Cách Mạng Tháng Tám',
        'Cao Thắng',
        'Công Trường Quốc Tế',
        'Điện Biên Phủ',
        'Đoàn Công Bửu',
        'Hoàng Sa',
        'Huỳnh Tịnh Của',
        'Huỳnh Văn Bánh',
        'Kỳ Đồng',
        'Lê Ngô Cát',
        'Lê Quý Đôn',
        'Lê Văn Sỹ',
        'Lý Chính Thắng',
        'Nam Kỳ Khởi Nghĩa',
        'Nguyễn Đình Chiểu',
        'Nguyễn Hiền',
        'Nguyễn Phúc Nguyên',
        'Nguyễn Sơn Hà',
        'Nguyễn Thị Diệu',
        'Nguyễn Thị Minh Khai',
        'Nguyễn Thiện Thuật',
        'Nguyễn Thông',
        'Nguyễn Thượng Hiền',
        'Pasteur',
        'Phạm Đình Toái',
        'Phạm Ngọc Thạch',
        'Rạch Bùng Binh',
        'Sư Thiện Chiếu',
        'Trần Cao Vân',
        'Trần Quang Diệu',
        'Trần Quốc Thảo',
        'Trần Quốc Toản',
        'Trần Văn Đang',
        'Trương Định',
        'Trương Quyền',
        'Trường Sa',
        'Tú Xương',
        'Võ Thị Sáu',
        'Võ Thị Tần',
        'Võ Văn Tần',
        'Vườn Chuối',
      ],
    },
    'Quận 4': {
      wards: [
        'Phường 1',
        'Phường 2',
        'Phường 3',
        'Phường 4',
        'Phường 5',
        'Phường 6',
        'Phường 8',
        'Phường 9',
        'Phường 10',
        'Phường 12',
        'Phường 13',
        'Phường 14',
        'Phường 15',
        'Phường 16',
        'Phường 18',
      ],
      streets: [
        'Tôn Đản',
        'Vĩnh Hội',
        'Nguyễn Tất Thành',
        'Hoàng Diệu',
        'Đoàn Văn Bơ',
        'Khánh Hội',
        'Lê Quốc Hưng',
        'Bến Vân Đồn',
        'Xóm Chiếu',
        'Đoàn Như Hài',
        'Nguyễn Khoái',
        'Tôn Thất Thuyết',
        'Đường 10C',
        'Đường 11',
        'Đường 12',
        'Đường 12A',
        'Đường 12B',
        'Đường 13',
        'Đường 15',
        'Đường 16',
        'Đường 17',
        'Đường 18',
        'Đường 29',
        'Đường 3',
        'Đường 30',
        'Đường 31',
        'Đường 32',
        'Đường 32A',
        'Đường 33',
        'Đường 34',
        'Đường 35',
        'Đường 36',
        'Đường 38',
        'Đường 39',
        'Đường 4',
        'Đường 40',
        'Đường 41',
        'Đường 45',
        'Đường 46',
        'Đường 47',
        'Đường 48',
        'Đường 49',
        'Đường 50',
        'Đường 6',
        'Đường 7',
        'Đường 8',
        'Đường 9',
        'Nguyễn Thần Hiến',
        'Nguyễn Trường Tộ',
        'Tân Vĩnh',
        'Trương Đình Hợi',
        'Vĩnh Khánh',
      ],
    },
    'Quận 5': {
      wards: [
        'Phường 1',
        'Phường 2',
        'Phường 3',
        'Phường 4',
        'Phường 5',
        'Phường 6',
        'Phường 7',
        'Phường 8',
        'Phường 9',
        'Phường 10',
        'Phường 11',
        'Phường 12',
        'Phường 13',
        'Phường 14',
        'Phường 15',
      ],
      streets: [
        'An Bình',
        'An Điềm',
        'An Dương Vương',
        'Bà Triệu',
        'Bạch Vân',
        'Bàn Cờ',
        'Bến Bãi Sậy',
        'Bùi Hữu Nghĩa',
        'Cao Đạt',
        'Châu Văn Liêm',
        'Chiêu Anh Các',
        'Đào Tấn',
        'Đặng Thái Thân',
        'Điện Biên Phủ',
        'Đỗ Ngọc Thạch',
        'Đỗ Văn Sửu',
        'Dương Tử Giang',
        'Gia Phú',
        'Gò Công',
        'Hà Tôn Quyền',
        'Hải Thượng Lãn Ông',
        'Hàm Tử',
        'Học Lạc',
        'Hồng Bàng',
        'Hùng Vương',
        'Huỳnh Mẫn Đạt',
        'Kim Biên',
        'Kỳ Đồng',
        'Lão Tử',
        'Lê Hồng Phong',
        'Lê Quang Định',
        'Lê Quang Sung',
        'Lê Thánh Tôn',
        'Lê Văn Sỹ',
        'Lương Nhữ Học',
        'Lưu Xuân Tín',
        'Lý Chính Thắng',
        'Lý Thường Kiệt',
        'Mạc Cửu',
        'Mạc Thiên Tích',
        'Nam Kỳ Khởi Nghĩa',
        'Nghĩa Thục',
        'Ngô Gia Tự',
        'Ngô Nhân Tịnh',
        'Ngô Quyền',
        'Nguyễn An Khương',
        'Nguyễn Biểu',
        'Nguyễn Chí Thanh',
        'Nguyễn Duy Dương',
        'Nguyễn Kim',
        'Nguyễn Sơn Hà',
        'Nguyễn Thi',
        'Nguyễn Thị Minh Khai',
        'Nguyễn Thị Nhỏ',
        'Nguyễn Thời Trung',
        'Nguyễn Trãi',
        'Nguyễn Tri Phương',
        'Nguyễn Văn Cừ',
        'Nguyễn Văn Đừng',
        'Nhiêu Tâm',
        'Pasteur',
        'Phạm Bân',
        'Phạm Đôn',
        'Phạm Hữu Chí',
        'Phan Huy Chú',
        'Phan Phú Tiên',
        'Phan Văn Khỏe',
        'Phan Văn Trị',
        'Phó Cơ Điều',
        'Phù Đổng Thiên Vương',
        'Phùng Hưng',
        'Phước Hưng',
        'Sư Vạn Hạnh',
        'Tạ Uyên',
        'Tản Đà',
        'Tân Hàng',
        'Tân Hưng',
        'Tân Thành',
        'Thuận Kiều',
        'Trang Tử',
        'Trần Bình Trọng',
        'Trần Chánh Chiếu',
        'Trần Điện',
        'Trần Hòa',
        'Trần Hưng Đạo',
        'Trần Nhân Tôn',
        'Trần Phú',
        'Trần Tuấn Khải',
        'Trần Tướng Công',
        'Trần Văn Kiểu',
        'Trần Xuân Hòa',
        'Triệu Quang Phục',
        'Trịnh Hoài Đức',
        'Vạn Kiếp',
        'Vạn Tượng',
        'Võ Trường Toản',
        'Võ Văn Kiệt',
        'Vũ Chí Hiếu',
        'Xóm Chỉ',
        'Xóm Vôi',
        'Yết Kiêu',
      ],
    },
    'Quận 6': {
      wards: [
        'Phường 1',
        'Phường 2',
        'Phường 3',
        'Phường 4',
        'Phường 5',
        'Phường 6',
        'Phường 7',
        'Phường 8',
        'Phường 9',
        'Phường 10',
        'Phường 11',
        'Phường 12',
        'Phường 13',
        'Phường 14',
      ],
      streets: [
        'An Dương Vương',
        'Bà Hom',
        'Bà Ký',
        'Bà Lài',
        'Bãi Sậy',
        'Bến Lò Gốm',
        'Bến Phú Lâm',
        'Bình Phú',
        'Bình Tây',
        'Bình Tiên',
        'Bửu Đình',
        'Cao Văn Lầu',
        'Chánh Hưng',
        'Chợ Lớn',
        'Chu Văn An',
        'Cư xá Phú Lâm A',
        'Cư xá Phú Lâm B',
        'Cư xá Phú Lâm D',
        'Đặng Nguyên Cẩn',
        'Đường 35C',
        'Đường số 1',
        'Đường số 10',
        'Đường số 10 Cư xá Rađa',
        'Đường số 11',
        'Đường số 12',
        'Đường số 14',
        'Đường số 15',
        'Đường số 18',
        'Đường số 19',
        'Đường số 2',
        'Đường số 20',
        'Đường số 22',
        'Đường số 23',
        'Đường số 24',
        'Đường số 26',
        'Đường số 28',
        'Đường số 28A',
        'Đường số 29',
        'Đường số 3',
        'Đường số 30',
        'Đường số 32',
        'Đường số 33',
        'Đường số 34',
        'Đường số 36',
        'Đường số 38',
        'Đường số 4',
        'Đường số 40',
        'Đường số 42',
        'Đường số 44',
        'Đường số 47',
        'Đường số 49',
        'Đường số 5',
        'Đường số 52',
        'Đường số 54',
        'Đường số 6',
        'Đường số 64',
        'Đường số 7',
        'Đường số 74',
        'Đường số 76',
        'Đường số 8',
        'Đường số 9',
        'Gia Phú',
        'Hậu Giang',
        'Hoàng Lê Kha',
        'Hồng Bàng',
        'Hùng Vương',
        'Kinh Dương Vương',
        'Lê Quang Sung',
        'Lê Tấn Kế',
        'Lê Trực',
        'Lê Tuấn Mậu',
        'Lò Gốm',
        'Lý Chiêu Hoàng',
        'Mai Xuân Thưởng',
        'Minh Phụng',
        'Ngô Nhân Tịnh',
        'Nguyễn Đình Chi',
        'Nguyễn Hữu Thận',
        'Nguyễn Ngọc Cung',
        'Nguyễn Phạm Tuân',
        'Nguyễn Thị Nhỏ',
        'Nguyễn Văn Luông',
        'Nguyễn Xuân Phụng',
        'Phạm Đình Hổ',
        'Phạm Phú Thứ',
        'Phạm Văn Chí',
        'Phan Anh',
        'Phan Văn Khỏe',
        'Phùng Hưng',
        'Song Hành',
        'Tân Hòa Đông',
        'Tháp Mười',
        'Tiền Chế',
        'Trần Bình',
        'Trần Trung Lập',
        'Trần Văn Kiểu',
        'Trang Tử',
        'Văn Thân',
        'Văn Thánh',
        'Vành Đai',
        'Võ Văn Kiệt',
      ],
    },

    'Quận 7': {
      wards: [
        'Phường Tân Thuận Đông',
        'Phường Tân Thuận Tây',
        'Phường Tân Kiểng',
        'Phường Tân Hưng',
        'Phường Tân Phong',
        'Phường Tân Phú',
        'Phường Phú Mỹ',
        'Phường Phú Thuận',
        'Phường Bình Thuận',
        'Phường Bình Khánh', // đôi khi dùng để chỉ khu vực ven cầu Tân Thuận, nhưng không phải phường chính thức – bạn có thể bỏ nếu muốn bám sát
      ],
      streets: [
        'Nguyễn Thị Thập',
        'Huỳnh Tấn Phát',
        'Trần Trọng Cung',
        'Lê Văn Lương',
        'Nguyễn Văn Linh',
        'Tân Mỹ',
        'Nguyễn Hữu Thọ',
        'Phú Thuận',
        'Tân Phú',
        'Hoàng Quốc Việt',
        'Đường số 1',
        'Đường số 2',
        'Đường số 3',
        'Đường số 4',
        'Đường số 5',
        'Đường số 6',
        'Đường số 7',
        'Đường số 8',
        'Đường số 9',
        'Đường số 10',
        'Đường số 11',
        'Đường số 12',
        'Đường số 13',
        'Đường số 14',
        'Đường số 15',
        'Đường số 16',
        'Đường số 17',
        'Đường số 18',
        'Đường số 19',
        'Đường số 20',
        'Đường số 21',
        'Đường số 22',
        'Đường số 23',
        'Đường số 24',
        'Đường số 25',
        'Đường số 26',
        'Đường số 27',
        'Đường số 28',
        'Đường số 29',
        'Đường số 30',
        'Đường số 31',
        'Đường số 32',
        'Đường số 33',
        'Đường số 34',
        'Đường số 35',
        'Đường số 36',
        'Đường số 37',
        'Đường số 38',
        'Đường số 39',
        'Đường số 40',
        'Đường số 41',
        'Đường số 42',
        'Đường số 43',
        'Đường số 44',
        'Đường số 45',
        'Đường số 46',
        'Đường số 47',
        'Đường số 48',
        'Đường số 49',
        'Đường số 50',
        'Đường số 51',
        'Đường số 52',
        'Đường số 53',
        'Đường số 54',
        'Đường số 55',
        'Đường số 56',
        'Đường số 57',
        'Đường số 58',
        'Đường số 59',
        'Đường số 60',
        'Đường số 61',
        'Đường số 62',
        'Đường số 63',
        'Đường số 64',
        'Đường số 65',
        'Đường số 66',
        'Đường số 67',
        'Đường số 68',
        'Đường số 69',
        'Đường số 70',
        'Đường số 71',
        'Đường số 72',
        'Đường số 73',
        'Đường số 74',
        'Đường số 75',
        'Đường số 76',
        'Đường số 77',
        'Đường số 78',
        'Đường số 79',
        'Đường số 80',
        'Đường số 81',
        'Đường số 82',
        'Đường số 83',
        'Đường số 84',
        'Đường số 85',
        'Đường số 86',
        'Đường số 87',
        'Đường số 88',
        'Đường số 89',
        'Đường số 90',
        'Đường số 91',
        'Đường số 92',
        'Đường số 93',
        'Đường số 94',
        'Đường số 95',
        'Đường số 96',
        'Đường số 97',
        'Đường số 98',
        'Đường số 99',
        'Đường số 100',
        'Đường số 101',
        'Đường số 102',
        'Đường số 103',
        'Đường số 104',
        'Đường số 105',
        'Đường số 106',
        'Đường số 107',
        'Đường số 108',
        'Đường số 109',
        'Đường số 110',
        'Đường số 111',
        'Đường số 112',
        'Đường số 113',
        'Đường số 114',
        'Đường số 115',
        'Đường số 116',
        'Đường số 117',
        'Đường số 118',
        'Đường số 119',
        'Đường số 120',
        'Đường số 121',
        'Đường số 122',
        'Đường số 123',
        'Đường số 124',
        'Đường số 125',
        'Đường số 126',
        'Đường số 127',
        'Đường số 128',
        'Đường số 129',
        'Đường số 130',
        'Đường số 131',
        'Đường số 132',
        'Đường số 133',
        'Đường số 134',
        'Đường số 135',
        'Đường số 136',
        'Đường số 137',
        'Đường số 138',
        'Đường số 139',
        'Đường số 140',
        'Đường số 141',
        'Đường số 142',
        'Đường số 143',
        'Đường số 144',
        'Đường số 145',
        'Đường số 146',
        'Đường số 147',
        'Đường số 148',
        'Đường số 149',
        'Đường số 150',
        'Đường số 151',
        'Đường số 152',
        'Đường số 153',
        'Đường số 154',
        'Đường số 155',
        'Đường số 156',
        'Đường số 157',
        'Đường số 158',
        'Đường số 159',
        'Đường số 160',
        'Đường số 161',
        'Đường số 162',
        'Đường số 163',
        'Đường số 164',
        'Đường số 165',
        'Đường số 166',
        'Đường số 167',
        'Đường số 168',
        'Đường số 169',
        'Đường số 170',
        'Đường số 171',
        'Đường số 172',
        'Đường số 173',
        'Đường số 174',
        'Đường số 175',
        'Đường số 176',
        'Đường số 177',
        'Đường số 178',
        'Đường số 179',
        'Đường số 180',
        'Đường số 181',
        'Đường số 182',
        'Đường số 183',
        'Đường số 184',
        'Đường số 185',
        'Đường số 186',
        'Đường số 187',
        'Đường số 188',
        'Đường số 189',
        'Đường số 190',
        'Đường số 191',
        'Đường số 192',
        'Đường số 193',
        'Đường số 194',
        'Đường số 195',
        'Đường số 196',
        'Đường số 197',
        'Đường số 198',
        'Đường số 199',
        'Đường số 200',
        'Đường số 201',
        'Đường số 202',
        'Đường số 203',
        'Đường số 204',
        'Đường số 205',
        'Đường số 206',
        'Đường số 207',
        'Đường số 208',
        'Đường số 209',
        'Đường số 210',
        'Đường số 211',
        'Đường số 212',
        'Đường số 213',
        'Đường số 214',
        'Đường số 215',
        'Đường số 216',
        'Đường số 217',
        'Đường số 218',
        'Đường số 219',
        'Đường số 220',
        'Đường số 221',
        'Đường số 222',
        'Đường số 223',
        'Đường số 224',
        'Đường số 225',
        'Đường số 226',
        'Đường số 227',
        'Đường số 228',
        'Đường số 229',
        'Đường số 230',
        'Đường số 231',
        'Đường số 232',
        'Đường số 233',
        'Đường số 234',
        'Đường số 235',
        'Đường số 236',
        'Đường số 237',
        'Đường số 238',
        'Đường số 239',
        'Đường số 240',
        'Đường số 241',
        'Đường số 242',
        'Đường số 243',
        'Đường số 244',
        'Đường số 245',
        'Đường số 246',
        'Đường số 247',
        'Đường số 248',
        'Đường số 249',
        'Đường số 250',
        'Đường số 251',
        'Đường số 252',
        'Đường số 253',
      ],
    },
    'Quận 8': {
      wards: [
        'Phường 1',
        'Phường 2',
        'Phường 3',
        'Phường 4',
        'Phường 5',
        'Phường 6',
        'Phường 7',
        'Phường 8',
        'Phường 9',
        'Phường 10',
        'Phường 11',
        'Phường 12',
        'Phường 13',
        'Phường 14',
        'Phường 15',
        'Phường 16',
      ],
      streets: [
        'Phạm Thế Hiển',
        'Tạ Quang Bửu',
        'Dương Bá Trạc',
        'Nguyễn Duy',
        'Âu Dương Lân',
        'Hoàng Ngân',
        'Ba Tơ',
        'Trịnh Quang Nghị',
        'Nguyễn Thị Tần',
        'Hưng Phú',
        'Bông Sao',
        'Cao Lỗ',
        'Nguyễn Văn Của',
        'Bùi Minh Trực',
        'Nguyễn Chế Nghĩa',
        'Bình Đông',
      ],
    },
    'Quận 10': {
      wards: [
        'Phường 1',
        'Phường 2',
        'Phường 3',
        'Phường 4',
        'Phường 5',
        'Phường 6',
        'Phường 7',
        'Phường 8',
        'Phường 9',
        'Phường 10',
        'Phường 11',
        'Phường 12',
        'Phường 13',
        'Phường 14',
        'Phường 15',
      ],
      streets: [
        'Nguyễn Tri Phương',
        'Ba Tháng Hai',
        'Lý Thường Kiệt',
        'Ngô Gia Tự',
        'Nguyễn Kim',
        'Tô Hiến Thành',
        'Sư Vạn Hạnh',
        'Điện Biên Phủ',
        'Trần Nhân Tôn',
        'Vĩnh Viễn',
        'Hùng Vương',
        'Cách Mạng Tháng Tám',
        'Lê Hồng Phong',
        'Lý Thái Tổ',
        'Trần Minh Quyền',
        'Trần Hưng Đạo',
      ],
    },

    'Quận 11': {
      wards: [
        'Phường 1',
        'Phường 2',
        'Phường 3',
        'Phường 4',
        'Phường 5',
        'Phường 6',
        'Phường 7',
        'Phường 8',
        'Phường 9',
        'Phường 10',
        'Phường 11',
        'Phường 12',
        'Phường 13',
        'Phường 14',
        'Phường 15',
        'Phường 16',
      ],
      streets: [
        'Lạc Long Quân',
        'Hàn Hải Nguyên',
        'Ông Ích Khiêm',
        'Ba Tháng Hai',
        'Hòa Bình',
        'Tân Hóa',
        'Bình Thới',
        'Lý Thường Kiệt',
        'Minh Phụng',
        'Thiên Hộ Dương',
        'Tuệ Tĩnh',
        'Âu Cơ',
        'Đội Cung',
        'Xóm Đất',
        'Nguyễn Thị Nhỏ',
        'Phó Cơ Điều',
        'Trịnh Đình Trọng',
        'Lê Đại Hành',
        'Thái Phiên',
        'Nguyễn Văn Phú',
      ],
    },

    'Quận 12': {
      wards: [
        'Phường An Phú Đông',
        'Phường Đông Hưng Thuận',
        'Phường Hiệp Thành',
        'Phường Tân Chánh Hiệp',
        'Phường Tân Hưng Thuận',
        'Phường Tân Thới Hiệp',
        'Phường Tân Thới Nhất',
        'Phường Thạnh Lộc',
        'Phường Thạnh Xuân',
        'Phường Thới An',
        'Phường Trung Mỹ Tây',
      ],
      streets: [
        'Lê Văn Khương',
        'Nguyễn Ảnh Thủ',
        'Tô Ký',
        'Trường Chinh',
        'Hà Huy Giáp',
        'Nguyễn Văn Quá',
        'Dương Thị Mười',
        'Song Hành Quốc Lộ 22',
        'Lê Thị Riêng',
        'QL1A',
        'Nguyễn Thị Búp',
        'Nguyễn Thị Đặng',
        'Huỳnh Thị Hai',
        'Vườn Lài',
        'Phan Văn Hớn',
        'Hẻm 539 Lê Văn Khương',
      ],
    },
    'Bình Thạnh': {
      wards: [
        'Phường 1',
        'Phường 2',
        'Phường 3',
        'Phường 5',
        'Phường 6',
        'Phường 7',
        'Phường 11',
        'Phường 12',
        'Phường 13',
        'Phường 14',
        'Phường 15',
        'Phường 17',
        'Phường 19',
        'Phường 21',
        'Phường 22',
        'Phường 24',
        'Phường 25',
        'Phường 26',
        'Phường 27',
        'Phường 28',
      ],
      streets: [
        'Điện Biên Phủ',
        'Xô Viết Nghệ Tĩnh',
        'Nguyễn Hữu Cảnh',
        'Đinh Bộ Lĩnh',
        'Bạch Đằng',
        'Nguyễn Văn Đậu',
        'Phan Văn Trị',
        'Phạm Viết Chánh',
        'Ung Văn Khiêm',
        'Nơ Trang Long',
        'Chu Văn An',
        'Lê Quang Định',
        'Trục đường D2 (Nguyễn Gia Trí)',
        'Trục đường D5 (Hoàng Diệu 2)',
        'Trục đường D1',
        'Vũ Huy Tấn',
        'Nguyễn Cửu Vân',
        'Hoàng Hoa Thám',
        'Trường Sa',
        'Bùi Đình Túy',
        'Nguyễn Thiện Thuật',
        'Nguyễn Trung Trực',
      ],
    },

    'Quận Gò Vấp': {
      wards: [
        'Phường 1',
        'Phường 3',
        'Phường 4',
        'Phường 5',
        'Phường 6',
        'Phường 7',
        'Phường 8',
        'Phường 9',
        'Phường 10',
        'Phường 11',
        'Phường 12',
        'Phường 13',
        'Phường 14',
        'Phường 15',
        'Phường 16',
        'Phường 17',
      ],
      streets: [
        'Quang Trung',
        'Phan Văn Trị',
        'Lê Đức Thọ',
        'Nguyễn Oanh',
        'Nguyễn Kiệm',
        'Nguyễn Văn Lượng',
        'Thống Nhất',
        'Phạm Văn Chiêu',
        'Trần Thị Nghỉ',
        'Lê Văn Thọ',
        'Dương Quảng Hàm',
        'Phạm Huy Thông',
        'Tân Sơn',
        'Cây Trâm',
        'Nguyễn Thái Sơn',
        'Lê Hoàng Phái',
        'Lê Lai',
        'Nguyễn Văn Công',
      ],
    },
    'Tân Bình': {
      wards: [
        'Phường 1',
        'Phường 2',
        'Phường 3',
        'Phường 4',
        'Phường 5',
        'Phường 6',
        'Phường 7',
        'Phường 8',
        'Phường 9',
        'Phường 10',
        'Phường 11',
        'Phường 12',
        'Phường 13',
        'Phường 14',
        'Phường 15',
      ],
      streets: [
        'Cộng Hòa',
        'Trường Chinh',
        'Hoàng Văn Thụ',
        'Lý Thường Kiệt',
        'Phổ Quang',
        'Bạch Đằng',
        'Tân Sơn Hòa',
        'Tân Kỳ Tân Quý',
        'Tây Thạnh',
        'Trường Sơn',
        'Út Tịch',
        'Ni Sư Huỳnh Liên',
        'Nguyễn Thái Bình',
        'Phạm Văn Bạch',
        'Giải Phóng',
        'Chấn Hưng',
        'Lê Trung Nghĩa',
        'Nguyễn Hồng Đào',
      ],
    },

    'Tân Phú': {
      wards: [
        'Phường Tân Sơn Nhì',
        'Phường Tây Thạnh',
        'Phường Sơn Kỳ',
        'Phường Tân Quý',
        'Phường Tân Thành',
        'Phường Phú Thọ Hòa',
        'Phường Phú Thạnh',
        'Phường Phú Trung',
        'Phường Hòa Thạnh',
        'Phường Hiệp Tân',
        'Phường Tân Thới Hòa',
      ],
      streets: [
        'Lũy Bán Bích',
        'Âu Cơ',
        'Thống Nhất',
        'Tân Kỳ Tân Quý',
        'Tân Hương',
        'Gò Dầu',
        'Nguyễn Sơn',
        'Thạch Lam',
        'Vườn Lài',
        'Trịnh Đình Trọng',
        'Trương Vĩnh Ký',
        'Độc Lập',
        'Hòa Bình',
        'Đoàn Giỏi',
        'Nguyễn Cửu Đàm',
        'Lê Sát',
      ],
    },
    'Bình Tân': {
      wards: [
        'Phường An Lạc',
        'Phường An Lạc A',
        'Phường Bình Hưng Hòa',
        'Phường Bình Hưng Hòa A',
        'Phường Bình Hưng Hòa B',
        'Phường Bình Trị Đông',
        'Phường Bình Trị Đông A',
        'Phường Bình Trị Đông B',
        'Phường Tân Tạo',
        'Phường Tân Tạo A',
      ],
      streets: [
        'Kinh Dương Vương',
        'Hương Lộ 2',
        'Tỉnh Lộ 10',
        'Mã Lò',
        'Lê Văn Quới',
        'Tân Kỳ Tân Quý',
        'Lê Trọng Tấn',
        'Liên Khu 5-6',
        'Liên Khu 10-11',
        'Đường số 7',
        'Đường số 17',
        'Đường số 54',
        'Võ Văn Vân',
        'Nguyễn Thị Tú',
        'Tây Lân',
        'An Dương Vương',
        'Trần Văn Giàu',
        'Số 1',
        'Số 8',
        'Số 14',
      ],
    },
    'Thành phố Thủ Đức': {
      wards: [
        'Phường An Khánh',
        'Phường An Lợi Đông',
        'Phường An Phú',
        'Phường Bình Chiểu',
        'Phường Bình Thọ',
        'Phường Cát Lái',
        'Phường Hiệp Bình Chánh',
        'Phường Hiệp Bình Phước',
        'Phường Hiệp Phú',
        'Phường Linh Chiểu',
        'Phường Linh Đông',
        'Phường Linh Tây',
        'Phường Linh Trung',
        'Phường Linh Xuân',
        'Phường Long Bình',
        'Phường Long Phước',
        'Phường Long Thạnh Mỹ',
        'Phường Long Trường',
        'Phường Phú Hữu',
        'Phường Phước Bình',
        'Phường Phước Long A',
        'Phường Phước Long B',
        'Phường Tam Bình',
        'Phường Tam Phú',
        'Phường Tân Phú',
        'Phường Thảo Điền',
        'Phường Thủ Thiêm',
        'Phường Trường Thạnh',
        'Phường Trường Thọ',
      ],
      streets: [
        'Xa Lộ Hà Nội',
        'Lê Văn Việt',
        'Đỗ Xuân Hợp',
        'Phạm Văn Đồng',
        'Nguyễn Duy Trinh',
        'Tô Ngọc Vân',
        'Kha Vạn Cân',
        'Võ Văn Ngân',
        'Nguyễn Văn Bá',
        'Man Thiện',
        'Hồ Bá Phấn',
        'Bình Thái',
        'Tăng Nhơn Phú',
        'Trường Sa',
        'Song Hành Xa Lộ',
        'Nguyễn Xiển',
        'Nguyễn Văn Tăng',
        'Lê Văn Thịnh',
        'Bưng Ông Thoàn',
        'Gò Dưa',
        'Tân Sơn Nhất – Bình Lợi',
        'Tam Hà',
        'Nguyễn Hoàng',
        'Trần Não',
      ],
    },

    'Huyện Bình Chánh': {
      wards: [
        'Xã An Phú Tây',
        'Xã Bình Chánh',
        'Xã Bình Hưng',
        'Xã Bình Lợi',
        'Xã Đa Phước',
        'Xã Hưng Long',
        'Xã Lê Minh Xuân',
        'Xã Phạm Văn Hai',
        'Xã Phong Phú',
        'Xã Quy Đức',
        'Xã Tân Kiên',
        'Xã Tân Nhựt',
        'Xã Tân Quý Tây',
        'Xã Vĩnh Lộc A',
        'Xã Vĩnh Lộc B',
      ],
      streets: [
        'Nguyễn Văn Linh',
        'Quách Điêu',
        'Đoàn Nguyễn Tuấn',
        'Trần Đại Nghĩa',
        'Võ Văn Vân',
        'Liên Ấp 1-2-3',
        'Tỉnh Lộ 10',
        'Tỉnh Lộ 8',
        'Tỉnh Lộ 50',
        'Nguyễn Hữu Trí',
        'Mai Bá Hương',
        'Láng Le – Bàu Cò',
        'Lê Đình Chi',
        'Hương Lộ 11',
        'Hương Lộ 80',
        'Kênh Trung Ương',
      ],
    },

    'Huyện Cần Giờ': {
      wards: [
        'Thị trấn Cần Thạnh',
        'Xã An Thới Đông',
        'Xã Bình Khánh',
        'Xã Long Hòa',
        'Xã Lý Nhơn',
        'Xã Tam Thôn Hiệp',
        'Xã Thạnh An',
      ],
      streets: ['Rừng Sác', 'Tắc Xuất', 'Duyên Hải', 'Đào Cử', 'Tỉnh Lộ 15C'],
    },
    'Huyện Củ Chi': {
      wards: [
        'Thị trấn Củ Chi',
        'Xã An Nhơn Tây',
        'Xã An Phú',
        'Xã Bình Mỹ',
        'Xã Hòa Phú',
        'Xã Nhuận Đức',
        'Xã Phạm Văn Cội',
        'Xã Phú Hòa Đông',
        'Xã Phước Hiệp',
        'Xã Phước Thạnh',
        'Xã Phước Vĩnh An',
        'Xã Tân An Hội',
        'Xã Tân Phú Trung',
        'Xã Tân Thạnh Đông',
        'Xã Tân Thạnh Tây',
        'Xã Tân Thông Hội',
        'Xã Thái Mỹ',
        'Xã Trung An',
        'Xã Trung Lập Hạ',
        'Xã Trung Lập Thượng',
      ],
      streets: [
        'Tỉnh Lộ 8',
        'Tỉnh Lộ 15',
        'Nguyễn Văn Khạ',
        'Quốc Lộ 22',
        'Nguyễn Thị Rành',
        'Lê Minh Nhựt',
      ],
    },

    'Huyện Hóc Môn': {
      wards: [
        'Thị trấn Hóc Môn',
        'Xã Bà Điểm',
        'Xã Đông Thạnh',
        'Xã Nhị Bình',
        'Xã Tân Hiệp',
        'Xã Tân Thới Nhì',
        'Xã Tân Xuân',
        'Xã Thới Tam Thôn',
        'Xã Trung Chánh',
        'Xã Xuân Thới Đông',
        'Xã Xuân Thới Sơn',
        'Xã Xuân Thới Thượng',
      ],
      streets: [
        'Nguyễn Ảnh Thủ',
        'Phan Văn Hớn',
        'Song Hành Quốc Lộ 22',
        'Lê Lợi',
        'Đặng Thúc Vịnh',
        'Đỗ Văn Dậy',
        'Trần Văn Mười',
      ],
    },
    'Huyện Nhà Bè': {
      wards: [
        'Thị trấn Nhà Bè',
        'Xã Hiệp Phước',
        'Xã Long Thới',
        'Xã Nhơn Đức',
        'Xã Phú Xuân',
        'Xã Phước Kiển',
        'Xã Phước Lộc',
      ],
      streets: ['Nguyễn Hữu Thọ', 'Huỳnh Tấn Phát', 'Lê Văn Lương', 'Nguyễn Bình', 'Phạm Hữu Lầu'],
    },
  },
} as const;
