export const breadcrumbConfig: Record<string, string> = {
    "/": "Trang chủ",                
    "/register": "Đăng ký",           
    "/login": "Đăng nhập",            
    "/wishlist": "Danh sách yêu thích", 
    "/product": "Sản phẩm",
    "/aboutus": "Về chúng tôi",
    "/profile": "Thông tin tài khoản",
    "/productdetail": "Chi tiết sản phẩm",    
    "/menu": "Thực đơn",
    "/profile/address": "Sổ địa chỉ",
    "/posts": "Bài viết",
    "/profile/orders": "Đơn hàng của tôi",
    "/cart": "Giỏ hàng",
    "/contact": "Liên hệ",
    "/reservation" : "Đặt bàn",
    "/favorites" : "Danh sách yêu thích",
    "/checkout": "Thanh toán",
    "/confirm": "Xác nhận đơn hàng",
    "/payment-success": "Thanh toán thành công",
    "/payment-failed": "Thanh toán thất bại",
    "/vouchers": "Chương trình khuyến mãi",    
    "/profile/my-reservation": "Lịch sử đặt bàn",
    "/reservation/lookup-reservation": "Tra cứu đặt bàn",
    "/foods": "Thực đơn",
  };
  